spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/transport # jdbc:mysql://${DB_URL}:3306/${DB_NAME}
    username: park # ${DB_USERNAME}
    password:  # ${DB_PASSWORD}
    driver-class-name: org.h2.Driver # com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto : none
    properties:
      hibernate:
        format_sql : true

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB


cloud:
  aws:
    credentials:
      accessKey: ${S3_ID}
      secretKey: ${S3_PASSWORD}
    s3:
      bucket: ${S3_NAME}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: debug


server:
  servlet:
    session:
      timeout: 36000
      tracking-modes: 'cookie'
