name: gradle and docker

on:
  workflow_dispatch:
    tag:
      description: 'description'
      required: false
      type: string

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
     
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build docker image and push to hub
        run: |
            VERSIONALL=$(cat argo/deployment.yaml | grep image)
            VERSION_SPLIT=($(echo $VERSIONALL | tr ":" "\n")) 
            VERSION=${VERSION_SPLIT[2]}
            rm -rf src/test
            gradle build
            docker build -t road-helper:0.1 .
            images_id=$(docker images -qa road-helper:0.1)
            docker tag $images_id wjdqlsdlsp/road-helper:$VERSION
            docker push wjdqlsdlsp/road-helper:$VERSION
